server:
  port: 8090

your-delivery:
  aws:
    access-key: ACCESS_KEY
    secret-key: SECRET_ACCESS_KEY
    region: eu-central-1
    endpoint: http://192.168.99.100:4566
    sns:
      topic-arn: arn:aws:sns:eu-central-1:000000000000:delivery
