spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:default}

server:
  port: ${SERVER_PORT:8090}

your-delivery:
  aws:
    access-key: ${ACCESS_KEY:ACCESS_KEY}
    secret-key: ${SECRET_ACCESS_KEY:SECRET_ACCESS_KEY}
    region: ${REGION:eu-central-1}
    sns:
      topic-arn: ${TOPIC_ARN}
      endpoint:
