version: "3.7"

services:
  localstack:
    image: localstack/localstack:2.0.2
    container_name: localstack
    ports:
      - "4566-4597:4566-4597"
    environment:
      SERVICES: sns,sqs
      AWS_DEFAULT_REGION: eu-central-1
