server:
  port: 8095

your-delivery:
  aws:
    access-key: ACCESS_KEY
    secret-key: SECRET_ACCESS_KEY
    region: eu-central-1
    sqs:
      endpoint: http://192.168.99.100:4566
      queue-url: http://192.168.99.100:4566/000000000000/notification
