spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:default}

server:
  port: ${SERVER_PORT:8095}

logging:
  file:
    path: ${LOG_FILE_PATH:/home/your-delivery-consumer}
    name: ${LOG_FILE_NAME:/home/your-delivery-consumer/consumer.log}

your-delivery:
  aws:
    access-key: ${ACCESS_KEY:ACCESS_KEY}
    secret-key: ${SECRET_ACCESS_KEY:SECRET_ACCESS_KEY}
    region: ${REGION:eu-central-1}
    sqs:
      queue-url: ${QUEUE_URL}
      endpoint:
