spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:default}

server:
  port: ${SERVER_PORT:8095}

your-delivery:
  aws:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_ACCESS_KEY}
    region: ${REGION:eu-central-1}
    sqs:
      queue-url: ${QUEUE_URL}
      endpoint:
